const crypto = require("crypto")

const { handleMultiplierPayoutStack }  = require("../utils/multiplierStack")

class GameEngine {
    constructor(gameConfig, databaseManager, rngEngine) {
        this.gameConfig = gameConfig
        this.databaseManager = databaseManager
        this.rngEngine = rngEngine

    }



    /*
     * Function to create a cell symbol for 6x5 board
     * @params {string} clientSeed -> clientSeed given by user
     * @params {string} serverSeed -> serverSeed generated by server per user session
     * @params {number} nonce -> nonce give by server
     * @return {string []} -> return an array of symbol names of size 30.
    */
    async generateBoard({clientSeed, serverSeed, nonce}) {

        // generate hex key for provably fair algorithm
        const randomKey = await this.rngEngine.generateHexKey({clientSeed, serverSeed, nonce})


        const board = []
        const totalCell = this.gameConfig.reels * this.gameConfig.row;

        for(let i = 0; i < totalCell; i++) {

            // slice 8 hex character from random key of 
            const slicedKey = randomKey.slice(i * 8, i*8 +8)

            // normalize it decimal value between [0, 1]
            const symbolProbability = (parseInt(slicedKey, 16)) / Math.pow(16, 8);

            // use that random value to generate random symbol
            const symbolName = this.rngEngine.generateRandomSymbol(symbolProbability);


            board.push(symbolName)
        }

        return board
    }

    /*
     * Function to check if the board has any winning symbol and cascade the board
    * @params {string []} board -> array of symbol names of size 30.
    * 
    */

    async checkWinandCascade({board, clientSeed, serverSeed, nonce, tumbleIndex}) {

        const symbolCounts = new Map();
        for (let i = 0; i < board.length; i++) {
            const symbol = board[i];
            symbolCounts.set(symbol, (symbolCounts.get(symbol) || 0) + 1);
        }

        const winningEntries = Array.from(symbolCounts)
            .filter(([name, count]) => {
                if (name === this.gameConfig.symbolName.SCATTER) return count >= 4;
                return count >= 8;
            });

        const winSymbol = new Map(winningEntries);

        


        // work on a COPY so the caller's original board stays intact for display
        const workingBoard = [...board];
        for (let i = 0; i < workingBoard.length; i++) {
            if (winSymbol.has(workingBoard[i])) {
                workingBoard[i] = null;
            }
        }

        const { reels, row } = this.gameConfig;
        const newBoard = Array(reels * row).fill(null);

        for (let r = 0; r < reels; r++) {
            const colStart = r * row;
            let writeIndex = colStart + row - 1;

            for (let i = colStart + row - 1; i >= colStart; i--) {
                if (workingBoard[i] !== null) {
                    newBoard[writeIndex] = workingBoard[i];
                    writeIndex--;
                }
            }

            while (writeIndex >= colStart) {
                const drawId = `${nonce}-${tumbleIndex}-${writeIndex}`;
                const hexKey = await this.rngEngine.generateHexKey({ clientSeed, serverSeed, nonce: drawId });
                const symbolProbability = parseInt(hexKey.slice(0, 8), 16) / Math.pow(16, 8);
                newBoard[writeIndex] = this.rngEngine.generateRandomSymbol(symbolProbability);
                writeIndex--;
            }
        }

        return { winSymbol, newBoard};
    }


    /* simulate actual spin of the game and return the result
     * @params {string} userId -> userId of the player
     * @params {string} clientSeed -> clientSeed given by user
     * @params {string} serverSeed -> serverSeed generated by server per user session
     * @params {number} nonce -> nonce give by server
     * @return {boardState: [], tumbles: number} -> return an array of board states and number of tumbles. Each board state contains the board and the winning symbols with their counts.
     */
    async spinReel({userId, clientSeed, serverSeed, nonce}) {

        let tumbles = 0;
        let board = await this.generateBoard({clientSeed, serverSeed, nonce});

        // {board: [], matchSymbol: {name: string, count: number}[]}[]
        let boardState = [];

        let shouldTumble = true;

        let shouldStartFreeSpin = {
            base : (board.filter(symbol => symbol === this.gameConfig.symbolName.SCATTER).length >= this.gameConfig.freespin.base.count),
            additional: (board.filter(symbol => symbol === this.gameConfig.symbolName.SCATTER).length >= this.gameConfig.freespin.additional.count)
        };

        // const multiplierPayoutStack = Array(this.gameConfig.reels).fill([]);
        const multiplierPayoutStack = Array.from({ length: this.gameConfig.reels }, () => []);


        await handleMultiplierPayoutStack({board, multiplierPayoutStack, clientSeed, serverSeed, nonce, tumbleIndex: tumbles});



        while(shouldTumble) {

            shouldTumble = false;

            // check for win and cascade

            const {winSymbol, newBoard} = await this.checkWinandCascade({board, clientSeed, serverSeed, nonce, tumbleIndex: tumbles});
            if(winSymbol.size > 0) {
                
                shouldTumble = true;
                tumbles++;
                boardState.push({board, matchSymbol: Array.from(winSymbol.entries()).map(([name, count]) => ({name, count}))});
                board = newBoard;

                // check if the new board has enough scatter symbols to trigger free spins
                shouldStartFreeSpin = {
                    base : (board.filter(symbol => symbol === this.gameConfig.symbolName.SCATTER).length >= this.gameConfig.freespin.base.count),
                    additional: (board.filter(symbol => symbol === this.gameConfig.symbolName.SCATTER).length >= this.gameConfig.freespin.additional.count)
                };

                await handleMultiplierPayoutStack({board, multiplierPayoutStack, clientSeed, serverSeed, nonce, tumbleIndex: tumbles});

            } else {
                boardState.push({board, matchSymbol: []});
            }

           
        }

        return {
            boardState,
            tumbles,
            multiplierPayoutStack,
            shouldStartFreeSpin
        }


    }


}



module.exports = GameEngine

